#Setting artifacts root directory and all the necessary directories
artifacts_root: artifacts

#Data ingestion repositories
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/samaTech-sys/Predictive-Policing-Advisory/raw/main/Kampala_Theft_Dataset.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Data Validation repositories
data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Kampala_Theft_Dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt


#Data processing Repositories 
data_processing:
  root_dir: artifacts/data_processing
  selected_data_file: artifacts/data_processing/selected_features.csv
  validation_report: artifacts/data_validation/selected_features_validation_report.txt